package flow;

public class FlowFeatures {
    public byte protocol;
    public int flowDuration;
    public int totalFwdPackets;
    public short totalBackwardPackets;
    public float fwdPacketsLengthTotal;
    public float bwdPacketsLengthTotal;
    public float fwdPacketLengthMax;
    public float fwdPacketLengthMin;
    public float fwdPacketLengthStd;
    public float bwdPacketLengthMax;
    public float bwdPacketLengthMin;
    public double flowBytesPerS;
    public double flowPacketsPerS;
    public float flowIATMean;
    public float flowIATMin;
    public float fwdIATTotal;
    public float fwdIATMean;
    public float fwdIATMin;
    public float bwdIATTotal;
    public float bwdIATMean;
    public float bwdIATMin;
    public long fwdHeaderLength;
    public long bwdHeaderLength;
    public float bwdPacketsPerS;
    public float packetLengthMax;
    public float packetLengthMean;
    public byte synFlagCount;
    public byte ackFlagCount;
    public byte urgFlagCount;
    public float downUpRatio;
    public float activeMean;
    public float activeStd;
    public float activeMax;
    public float activeMin;
    public float idleMean;
    public float idleStd;
    public float idleMax;
}